version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-edge-dist2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1882ei3cfmxkc"
s3_prefix = "lambda-edge-dist2"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

