AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A/B testing using cloudfront and lambda@edge

Parameters:
  OriginAccessIdentity:
    Type: String

Resources:

  OriginABucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ab-test-a
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
      Tags:
      - Key: purpose
        Value: lab
      - Key: project
        Value: lambda-edge-ab

  OriginBBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ab-test-b
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
      Tags:
      - Key: purpose
        Value: lab
      - Key: project
        Value: lambda-edge-ab

  OriginAAccessBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: OriginABucket
      PolicyDocument:
        Version: '2008-10-17'
        Id: PolicyForCloudFrontPrivateContentA
        Statement:
        - Sid: '1'
          Effect: Allow
          Principal:
            CanonicalUser: !Ref OriginAccessIdentity
          Action: s3:GetObject
          Resource: 
            - !Join [ "", [ "arn:aws:s3:::", !Ref OriginABucket, "/*"]]
            # - !Join [ "", [ "arn:aws:s3:::", !Ref OriginBBucket, "/*"]] 

  OriginBAccessBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: OriginBBucket
      PolicyDocument:
        Version: '2008-10-17'
        Id: PolicyForCloudFrontPrivateContentA
        Statement:
        - Sid: '1'
          Effect: Allow
          Principal:
            CanonicalUser: !Ref OriginAccessIdentity
          Action: s3:GetObject
          Resource: 
            - !Join [ "", [ "arn:aws:s3:::", !Ref OriginBBucket, "/*"]] 

Outputs:
  BucketADomain:
    Description: Regional Domian name of the A bucket
    Value: !GetAtt OriginABucket.RegionalDomainName
  BucketBDomain:
    Description: Regional Domian name of the A bucket
    Value: !GetAtt OriginBBucket.RegionalDomainName