version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-edge-tracker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p5w39ue2smf"
s3_prefix = "lambda-edge-tracker"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

